  version: 2
  updates:
    - package-ecosystem: gradle
      directory: /
      schedule:
        interval: weekly
      target-branch: "main"
      commit-message:
        prefix: "[Dependabot]"
        include: scope
      reviewers:
        - vnastasi
