name: "Code coverage"

inputs:
  silent:
    description: "Flag indicating whether code coverage report should be created silently. If set to false, it will not be published and will not fail the workflow run."
    required: true
    default: "false"

runs:
  using: composite
  steps:
    - name: "Create report"
      shell: bash
      run: ./gradlew createCodeCoverageReport

    - name: "Archive coverage report"
      if: ${{ inputs.silent == 'false' }}
      uses: actions/upload-artifact@v4
      with:
        name: "code-coverage-report-${{ github.event.pull_request.number }}"
        path: ${{ github.workspace }}/build/reports/code-coverage
        if-no-files-found: error
        retention-days: 14
        overwrite: true

    - name: "Publish code coverage report"
      if: ${{ inputs.silent == 'false' }}
      uses: madrapps/jacoco-report@v1.7.2
      with:
        token: ${{ env.GH_TOKEN }}
        paths: ${{ github.workspace }}/build/reports/code-coverage/jacoco.xml
        update-comment: true
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        title: "🔍 Code coverage report"
        pass-emoji: 🟢
        fail-emoji: 🔴

    - name: "Fail on low code coverage"
      if: ${{ inputs.silent == 'false' }}
      shell: bash
      run: ./gradlew verifyCodeCoverage

    - name: "Update code coverage badge"
      if: ${{ inputs.silent == 'true' }}
      uses: cicirello/jacoco-badge-generator@v2.12.0
      with:
        jacoco-csv-file: build/reports/code-coverage/jacoco.csv
        coverage-label: "Code coverage"
        generate-workflow-summary: true
        workflow-summary-heading: "Code coverage summary"

    - name: "Commit changes"
      if: ${{ inputs.silent == 'true' }}
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Valentin Nastasi'
          git config --global user.email 'vnastasi@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated code coverage badge"
          git push
        fi
