name: "Code coverage"

inputs:
  update-badge:
    description: "Flag indicating whether this action should update the code coverage badge or not."
    required: true
    default: "false"

runs:
  using: composite
  steps:
    - name: "Create report"
      shell: bash
      run: ./gradlew createCodeCoverageReport

    - name: "Verify code coverage"
      if: ${{ inputs.update-badge == 'false' }}
      shell: bash
      run: ./gradlew verifyCodeCoverage

    - name: "Archive coverage report"
      if: ${{ inputs.update-badge == 'false' }}
      uses: actions/upload-artifact@v4
      with:
        name: "code-coverage-report-${{ github.event.pull_request.number }}"
        path: ${{ github.workspace }}/build/reports/code-coverage
        if-no-files-found: error
        retention-days: 14
        overwrite: true

    - name: "Update code coverage badge"
      if: ${{ inputs.update-badge == 'true' }}
      uses: cicirello/jacoco-badge-generator@v2.12.0
      with:
        jacoco-csv-file: build/reports/code-coverage/jacoco.csv
        coverage-label: "Code coverage"
        generate-workflow-summary: true
        workflow-summary-heading: "Code coverage summary"

    - name: "Commit changes"
      if: ${{ inputs.update-badge == 'true' }}
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Valentin Nastasi'
          git config --global user.email 'vnastasi@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated code coverage badge"
          git push
        fi
