[versions]

android-tools = "8.0.2"
androidx-activity = "1.7.2"
androidx-core = "1.10.1"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.6.0"
androidx-test-junit = "1.1.5"
compose-bom = "2023.06.01"
compose-kotlinCompilerExt = "1.4.8"
espresso = "3.5.1"
koin = "3.4.2"
kotlin = "1.8.22"
ksp = "1.8.22-1.0.11"
room = "2.5.2"


[libraries]

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lificycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-test = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-material = { module = "androidx.compose.material3:material3" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui = { module = "androidx.compose.ui:ui" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-test = { module = "io.insert-koin:koin-android-test", version.ref = "koin" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
room = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-test = { module = "androidx.room:room-testing", version.ref = "room" }


[plugins]

android-application = { id = "com.android.application", version.ref = "android-tools" }
android-library = { id = "com.android.library", version.ref = "android-tools" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


[bundles]