name: Create release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

jobs:
  create-artifact:
    name: "Create release artifact"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Set up development tools"
        uses: ./.github/actions/setup-dev-tools-action

      - name: "Create release artifact"
        shell: bash
        run: |
          ./gradlew assembleRelease
          ./gradlew copyReleaseApkArtifact

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "apk"
          path: build/artifacts/apk/shopping-list-${{ github.ref_name }}.apk
          if-no-files-found: error
          retention-days: 14
          overwrite: true

  release-artifact:
    name: "Release artifact"
    needs:
      - create-artifact
    runs-on: ubuntu-latest
    steps:
      - id: download-artifact
        name: "Download APK from build"
        uses: actions/download-artifact@v5
        with:
          name: "apk"

      - id: create-release
        name: "Create release"
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - id: upload-release-artifact
        name: "Upload release artifact"
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./shopping-list-${{ github.ref_name }}.apk
          asset_name: shopping-list-${{ github.ref_name }}.apk
          asset_content_type: application/zip
