name: Feature pull request Workflow

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize

jobs:
  build:
    name: "Build & Unit test"

    runs-on: ubuntu-latest

    steps:

      - name: "Environment"
        run: |
          echo "Agent ${{ runner.name }}"
          echo "Operating system ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

      - name: "Enable hardware acceleration"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Grant permissions"
        run: chmod +x gradlew

      - name: "Assemble application"
        run: ./gradlew assemble

      - name: "Unit tests"
        run: ./gradlew testReleaseUnitTest

      - name: "Assemble instrumented test application"
        run: ./gradlew assembleAndroidTest

      - name: "Run instrumented tests"
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest

      - name: "Code quality"
        run: ./gradlew detekt
