name: Pull request

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: "Build application"
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
    steps:
      - name: "Environment"
        run: |
          echo "Agent ${{ runner.name }}"
          echo "Operating system ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: "Grant permissions"
        run: chmod +x gradlew

      - name: "Assemble application"
        run: ./gradlew assemble

  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      CACHE_KEY: "unit-tests-exec-data"
    needs:
      - build
    steps:
      - name: "Environment"
        run: |
          echo "Agent ${{ runner.name }}"
          echo "Operating system ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Clear caches"
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete "$CACHE_KEY"

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: "Grant permissions"
        run: chmod +x gradlew

      - name: "Assemble unit tests"
        run: ./gradlew assembleDebugUnitTest

      - name: "Run unit tests"
        run: ./gradlew testDebugUnitTest

      - name: "Save test execution data"
        run: ./gradlew copyUnitTestExecData

      - name: "Cache test execution data"
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/build/exec-data/unit-tests
          key: ${{ env.CACHE_KEY }}

  instrumented-tests:
    name: "Instrumented tests"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      CACHE_KEY: "instrumented-tests-exec-data"
    needs:
      - build
    steps:
      - name: "Environment"
        run: |
          echo "Agent ${{ runner.name }}"
          echo "Operating system ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

      - name: "Enable hardware acceleration"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Clear caches"
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete "$CACHE_KEY"

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: "Grant permissions"
        run: chmod +x gradlew

      - name: "Assemble instrumented tests"
        run: ./gradlew assembleDebugAndroidTest

      - name: "Set up emulator caching"
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-35-google_apis

      - name: "Create emulator snapshot"
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated emulator snapshot."

      - name: "Run instrumented tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=md.vnastasi.shoppinglist.suite.AllSuite

      - name: "Save test execution data"
        run: ./gradlew copyInstrumentedTestExecData

      - name: "Cache test execution data"
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/build/exec-data/instrumented-tests
          key: ${{ env.CACHE_KEY }}

  code-quality:
    name: "Verify code quality"
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
    needs:
      - unit-tests
      - instrumented-tests
    steps:
      - name: "Environment"
        run: |
          echo "Agent ${{ runner.name }}"
          echo "Operating system ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: "Grant permissions"
        run: chmod +x gradlew

      - name: "Restore unit test execution data"
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/build/exec-data/unit-tests
          key: unit-tests-exec-data
          fail-on-cache-miss: true

      - name: "Restore instrumented test execution data"
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/build/exec-data/instrumented-tests
          key: instrumented-tests-exec-data
          fail-on-cache-miss: true

      - name: "Compile code"
        run: |
          ./gradlew compileDebugSources
          ./gradlew compileDebugUnitTestSources
          ./gradlew compileDebugAndroidTestSources

      - name: "Code coverage"
        run: ./gradlew verifyCodeCoverage

      - name: "Detekt"
        run: ./gradlew detekt

  dependabot:
    name: "Dependabot auto-merge"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs:
      - code-quality
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Auto-merge Dependabot PR"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --squash $PR_URL
