name: Feature pull request Workflow

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize

jobs:
  build:
    name: "Build & Unit test"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 30 ]

    steps:

      - name: "Environment"
        run: |
          echo "Agent ${{ runner.name }}"
          echo "Operating system ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

      - name: "Enable hardware acceleration"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Grant permissions"
        run: chmod +x gradlew

      - name: "Assemble application"
        run: ./gradlew assemble

      - name: "Unit tests"
        run: ./gradlew testReleaseUnitTest

      - name: "Assemble instrumented test application"
        run: ./gradlew assembleAndroidTest

      - name: "Set up emulator caching"
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: "Create emulator snapshot"
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated emulator snapshot."

      - name: "Run instrumented tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: "Code quality"
        run: ./gradlew detekt
