name: Initiate new release

on:
  workflow_dispatch:
    inputs:
      newAppVersion:
        type: string
        description: "New app version"
        required: true

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

jobs:
  initiate-release:
    name: "Initiate release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ secrets.RELEASEBOT_PAT }}

      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: "Update project version"
        run: ./gradlew updateProjectVersion -Pmd.vnastasi.shoppinglist.newAppVersion=${{ inputs.newAppVersion }}

      - name: "Verify project build"
        run: ./gradlew assemble

      - name: "Commit changes"
        run: |
          git config --global user.name "releasebot[bot]"
          git config --global user.email "releasebot@users.noreply.github.com"
          git commit -am "Prepare release for version ${{ inputs.newAppVersion }}"
          git push

      - name: "Create release tag"
        run: |
          git config --global user.name "releasebot[bot]"
          git config --global user.email "releasebot@users.noreply.github.com"
          git tag v${{ inputs.newAppVersion }}
          git push origin tag v${{ inputs.newAppVersion }}
