name: Update caches

on:
  push:
    branches:
      - "main"

jobs:
  gradle-cache:
    name: "Update Gradle cache"
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: "Assemble application"
        run: ./gradlew assemble

  emulator-cache:
    name: "Update emulator snapshot cache"
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        api-level: [35]
        target: [default]
    steps:
      - name: "Enable hardware acceleration"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Set up emulator caching"
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}

      - name: "Create emulator snapshot"
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated emulator snapshot."
