name: Update caches

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

jobs:

  update-emulator-cache:
    name: "Update emulator snapshot cache"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "Enable hardware acceleration"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Set up emulator caching"
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-35-default

      - name: "Create emulator snapshot"
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: default
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated emulator snapshot."

  update-coverage-badge:
    name: "Update code coverage badge"
    runs-on: ubuntu-latest
    needs:
      - update-emulator-cache
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Set up development tools"
        uses: ./.github/actions/setup-dev-tools-action

      - name: "Assemble application and tests"
        run: |
          ./gradlew assemble
          ./gradlew assembleDebugUnitTest
          ./gradlew assembleDebugAndroidTest

      - name: "Run unit tests"
        uses: ./.github/actions/run-unit-tests-action

      - name: "Run instrumented tests"
        uses: ./.github/actions/run-instrumented-tests-action
        with:
          avd-api-level: 35
          avd-target: default

      - name: "Create code coverage report"
        run: ./gradlew createCodeCoverageReport

      - name: "Update code coverage badge"
        uses: cicirello/jacoco-badge-generator@v2.12.0
        with:
          jacoco-csv-file: build/reports/code-coverage/jacoco.csv
          coverage-label: "Code coverage"
          generate-workflow-summary: true
          workflow-summary-heading: "Code coverage summary"

      - name: "Commit changes"
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Valentin Nastasi'
            git config --global user.email 'vnastasi@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated code coverage badge"
            git push
          fi
